// SUNDER: Ascension II — the Codex (DESIGN.md screen 7: "lore entries for every Keeper, ship and Hour, unlocked as you
// play"), as a reusable panel opened from the title and the pause menu. Its text is the web game's own
// (SunderCodexEntries.inl, generated by unreal/Tools/export_codex_text.cjs); what is unlocked is USunderCodexSubsystem's.
//   KEEPERS  the web Codex's row of portrait cards (a dark silhouette until met) · met: the portrait in its accent's
//            glow, name, title, Hour, quote · beaten: its lore, attacks and arena
//   HOURS    reached: name, act, quote, brief · its Keeper beaten: the Hour's closing line
//   SHIPS    always: class, personality, the three forms
#pragma once

#include "CoreMinimal.h"
#include "UObject/StrongObjectPtr.h"

class AHUD;
class UTexture2D;
class USunderCodexSubsystem;

struct FSunderCodexKeeper { int32 Hour; int32 Act; uint32 Accent; const TCHAR* Name; const TCHAR* Epithet; const TCHAR* HourLine; const TCHAR* Quote;
	const TCHAR* Lore; const TCHAR* Patterns; const TCHAR* Arena; const TCHAR* Portrait; };
struct FSunderCodexHour { int32 Num; const TCHAR* Name; const TCHAR* Act; const TCHAR* Quote; const TCHAR* Brief; const TCHAR* Clear; };
struct FSunderCodexShip { const TCHAR* Name; const TCHAR* Class; const TCHAR* Personality; const TCHAR* Forms; };

struct SUNDER2_API FSunderCodexPanel
{
	void Open(float Now);
	/** W / S move through the entries; A / D change tab. True when something moved (the owner may play a cue). */
	bool Navigate(int32 X, int32 Y, float Now);
	void Draw(AHUD* Hud, const USunderCodexSubsystem* Codex, float Now) const;

private:
	int32 Count() const;
	UTexture2D* Portrait(int32 i) const;
	void DrawKeepers(AHUD* Hud, const USunderCodexSubsystem* Codex, float PX, float PY, float PW, float PH, float A, float Now) const;
	float DrawWrapped(AHUD* Hud, const FString& Text, const FLinearColor& Color, float X, float Y, float Width, float Px) const;

	int32 Tab = 0;               // 0 Keepers, 1 Hours, 2 Ships
	int32 Index[3] = { 0, 0, 0 };
	float OpenedAt = 0.f;
	float MovedAt = -10.f;        // when the Keeper card last changed: the chosen card rises
	mutable TArray<TStrongObjectPtr<UTexture2D>> Portraits;   // loaded on first sight, kept while the panel lives
};
