extends Node
## StageData — the Nine Bows campaign.
## One source of truth for every stage: enemy stats, boss stats, colors, patterns.
## Difficulty scales up each stage via the numbers here.

# Faction colors (tint applied to shared sprites; swap for unique art later)
const STAGES: Array = [
	{
		"num": 1,
		"name": "The Nubians",
		"subtitle": "Archers of the South",
		"tint": Color(0.85, 0.55, 0.30),      # bronze
		# --- enemy wave ---
		"enemy_health": 2,
		"enemy_speed": 110.0,
		"enemy_fire_interval": 1.9,
		"enemy_move": "dive",                  # dive|weave|rush|zigzag|circle|formation|evade
		"enemy_bullet_speed": 210.0,
		"enemy_points": 100,
		"spawn_interval": 1.2,
		"drop_chance": 0.20,
		"score_to_boss": 2000,
		# --- boss ---
		"boss_name": "Archer King Taharqa",
		"boss_health": 180,
		"boss_points": 4000,
		"boss_patterns": ["aimed_volley"],
		"boss_fire_rate": 1.3,
		"boss_bullet_speed": 190.0,
		"boss_move_speed": 60.0,
	},
	{
		"num": 2,
		"name": "The Libyans",
		"subtitle": "Raiders of the Western Sands",
		"tint": Color(0.90, 0.80, 0.45),      # sand gold
		"enemy_health": 3,
		"enemy_speed": 125.0,
		"enemy_fire_interval": 1.7,
		"enemy_move": "weave",
		"enemy_bullet_speed": 230.0,
		"enemy_points": 120,
		"spawn_interval": 1.1,
		"drop_chance": 0.18,
		"score_to_boss": 2600,
		"boss_name": "Desert Warlord Meshwesh",
		"boss_health": 240,
		"boss_points": 5000,
		"boss_patterns": ["spread_fan", "aimed_volley"],
		"boss_fire_rate": 1.15,
		"boss_bullet_speed": 210.0,
		"boss_move_speed": 80.0,
	},
	{
		"num": 3,
		"name": "The Hyksos",
		"subtitle": "The Chariot Invaders",
		"tint": Color(0.70, 0.75, 0.85),      # steel blue
		"enemy_health": 3,
		"enemy_speed": 175.0,
		"enemy_fire_interval": 1.5,
		"enemy_move": "rush",
		"enemy_bullet_speed": 250.0,
		"enemy_points": 140,
		"spawn_interval": 1.0,
		"drop_chance": 0.17,
		"score_to_boss": 3200,
		"boss_name": "Chariot Lord Khyan",
		"boss_health": 300,
		"boss_points": 6000,
		"boss_patterns": ["horizontal_sweep", "spread_fan"],
		"boss_fire_rate": 1.0,
		"boss_bullet_speed": 230.0,
		"boss_move_speed": 110.0,
	},
	{
		"num": 4,
		"name": "The Sea Peoples",
		"subtitle": "Tide of the Broken Nations",
		"tint": Color(0.40, 0.75, 0.80),      # teal
		"enemy_health": 4,
		"enemy_speed": 150.0,
		"enemy_fire_interval": 1.4,
		"enemy_move": "zigzag",
		"enemy_bullet_speed": 260.0,
		"enemy_points": 160,
		"spawn_interval": 0.95,
		"drop_chance": 0.16,
		"score_to_boss": 3800,
		"boss_name": "Wave Tyrant Peleset",
		"boss_health": 360,
		"boss_points": 7000,
		"boss_patterns": ["radial_burst", "horizontal_sweep"],
		"boss_fire_rate": 0.9,
		"boss_bullet_speed": 240.0,
		"boss_move_speed": 100.0,
	},
	{
		"num": 5,
		"name": "The Hittites",
		"subtitle": "The Iron Empire",
		"tint": Color(0.60, 0.30, 0.30),      # iron red
		"enemy_health": 6,
		"enemy_speed": 130.0,
		"enemy_fire_interval": 1.3,
		"enemy_move": "dive",
		"enemy_bullet_speed": 270.0,
		"enemy_points": 200,
		"spawn_interval": 0.9,
		"drop_chance": 0.15,
		"score_to_boss": 4600,
		"boss_name": "Iron Charioteer Muwatalli",
		"boss_health": 440,
		"boss_points": 8500,
		"boss_patterns": ["cross_ring", "aimed_volley", "radial_burst"],
		"boss_fire_rate": 0.85,
		"boss_bullet_speed": 250.0,
		"boss_move_speed": 90.0,
	},
	{
		"num": 6,
		"name": "The Mitanni",
		"subtitle": "Masters of the Maryannu",
		"tint": Color(0.55, 0.45, 0.75),      # violet
		"enemy_health": 6,
		"enemy_speed": 160.0,
		"enemy_fire_interval": 1.2,
		"enemy_move": "circle",
		"enemy_bullet_speed": 285.0,
		"enemy_points": 220,
		"spawn_interval": 0.85,
		"drop_chance": 0.14,
		"score_to_boss": 5400,
		"boss_name": "Maryannu Rider Tushratta",
		"boss_health": 520,
		"boss_points": 10000,
		"boss_patterns": ["spiral", "spread_fan", "radial_burst"],
		"boss_fire_rate": 0.7,
		"boss_bullet_speed": 270.0,
		"boss_move_speed": 120.0,
	},
	{
		"num": 7,
		"name": "The Assyrians",
		"subtitle": "The Siege That Never Ends",
		"tint": Color(0.80, 0.25, 0.25),      # blood red
		"enemy_health": 7,
		"enemy_speed": 150.0,
		"enemy_fire_interval": 1.0,
		"enemy_move": "formation",
		"enemy_bullet_speed": 300.0,
		"enemy_points": 260,
		"spawn_interval": 0.75,
		"drop_chance": 0.13,
		"score_to_boss": 6400,
		"boss_name": "Siege King Ashurbanipal",
		"boss_health": 620,
		"boss_points": 12000,
		"boss_patterns": ["wall_barrage", "cross_ring", "spiral"],
		"boss_fire_rate": 0.6,
		"boss_bullet_speed": 285.0,
		"boss_move_speed": 100.0,
	},
	{
		"num": 8,
		"name": "The Persians",
		"subtitle": "The Immortal Host",
		"tint": Color(0.85, 0.65, 0.20),      # imperial gold
		"enemy_health": 8,
		"enemy_speed": 185.0,
		"enemy_fire_interval": 0.9,
		"enemy_move": "evade",
		"enemy_bullet_speed": 320.0,
		"enemy_points": 300,
		"spawn_interval": 0.7,
		"drop_chance": 0.12,
		"score_to_boss": 7600,
		"boss_name": "Immortal Shah Cambyses",
		"boss_health": 740,
		"boss_points": 15000,
		"boss_patterns": ["dual_spiral", "wall_barrage", "radial_burst"],
		"boss_fire_rate": 0.5,
		"boss_bullet_speed": 300.0,
		"boss_move_speed": 130.0,
	},
	{
		"num": 9,
		"name": "The Nine Bows United",
		"subtitle": "The Crystal Overlord Descends",
		"tint": Color(0.80, 0.30, 0.90),      # crystal magenta
		"enemy_health": 8,
		"enemy_speed": 175.0,
		"enemy_fire_interval": 0.85,
		"enemy_move": "zigzag",
		"enemy_bullet_speed": 330.0,
		"enemy_points": 350,
		"spawn_interval": 0.6,
		"drop_chance": 0.14,
		"score_to_boss": 9000,
		"boss_name": "THE CRYSTAL OVERLORD",
		"boss_health": 1000,
		"boss_points": 30000,
		"boss_patterns": ["dual_spiral", "wall_barrage", "cross_ring", "radial_burst", "spiral"],
		"boss_fire_rate": 0.4,
		"boss_bullet_speed": 320.0,
		"boss_move_speed": 140.0,
	},
]

static func get_stage(index: int) -> Dictionary:
	if index < 0 or index >= STAGES.size():
		return STAGES[STAGES.size() - 1]
	return STAGES[index]

static func stage_count() -> int:
	return STAGES.size()
