// SUNDER: Ascension II — writes the Unreal Codex's text (Source/Sunder2/Private/SunderCodexEntries.inl) from the web
// game: the Keeper Codex (web/keepers.html KEEPERS), the ships (web/game.html SHIPS) and the Hours
// (Content/Story/story.json, itself from export_story_text.cjs). Run from the repo:  node unreal/Tools/export_codex_text.cjs
// Re-run it whenever that text changes; the .inl is generated, don't edit it by hand.
const fs = require('fs');
const path = require('path');
const vm = require('vm');

const root = path.resolve(__dirname, '..', '..');                 // sunder-ascension-ii/
const readArray = (file, name) => {
  const src = fs.readFileSync(path.join(root, file), 'utf8');
  const start = src.indexOf('const ' + name + ' = [');
  if (start < 0) throw new Error(name + ' not found in ' + file);
  const end = src.indexOf('];', start);
  return vm.runInNewContext('[' + src.slice(start + ('const ' + name + ' = [').length, end) + ']');
};
const keepers = readArray('web/keepers.html', 'KEEPERS');
const ships = readArray('web/game.html', 'SHIPS');
const story = JSON.parse(fs.readFileSync(path.join(root, 'unreal/Content/Story/story.json'), 'utf8'));

const q = s => 'TEXT(' + JSON.stringify(String(s || '')) + ')';
const camel = id => id.split('_').map(p => p[0].toUpperCase() + p.slice(1)).join('');
const out = [];
out.push('// GENERATED by unreal/Tools/export_codex_text.cjs from web/keepers.html, web/game.html and story.json. Do not edit.');
out.push('// Included by SunderCodexPanel.cpp: the Codex\'s Keepers (one per Hour, with its act and accent colour), Hours and ships.');
out.push('');
out.push('static const FSunderCodexKeeper GCodexKeepers[] = {');
const finals = Object.fromEntries(keepers.filter(k => k.id.endsWith('_p3')).map(k => [k.id.replace(/_p3$/, ''), k]));
for (const k of keepers.filter(k => !k.id.endsWith('_p3'))) {
  const hourNum = parseInt(String(k.hour).match(/HOUR (\d+)/)[1], 10);
  let lore = k.brief;
  if (finals[k.id]) lore += '\n\n' + finals[k.id].epithet.toUpperCase() + ': ' + finals[k.id].brief + ' ' + finals[k.id].quote;
  const accent = '0x' + k.accent.toString(16).padStart(6, '0').toUpperCase();
  out.push(`\t{ ${hourNum}, ${k.act}, ${accent}, ${q(k.name)}, ${q(k.epithet)}, ${q(k.hour)}, ${q(k.quote)}, ${q(lore)}, ${q(k.patterns)}, ${q(k.arena)},`);
  out.push(`\t\t${q('/Game/Sunder/UI/Keepers/T_Portrait_' + camel(k.id) + '.T_Portrait_' + camel(k.id))} },`);
}
out.push('};');
out.push('');
out.push('static const FSunderCodexHour GCodexHours[] = {');
for (const h of story.hours) {
  out.push(`\t{ ${h.num}, ${q(h.name)}, ${q(h.subtitle)}, ${q(h.quote)}, ${q(h.brief)}, ${q(h.clear)} },`);
}
out.push('};');
out.push('');
out.push('static const FSunderCodexShip GCodexShips[] = {');
for (const s of ships) {
  out.push(`\t{ ${q(s.name)}, ${q(s.ship_class)}, ${q(s.personality)}, ${q(s.form_names.join('  →  '))} },`);
}
out.push('};');
const file = path.join(root, 'unreal/Source/Sunder2/Private/SunderCodexEntries.inl');
fs.writeFileSync(file, out.join('\n') + '\n');
console.log('wrote', path.relative(root, file), '-', keepers.length - Object.keys(finals).length, 'Keepers,', story.hours.length, 'Hours,', ships.length, 'ships');
